config/routes.rb
Rails.application.routes.draw do

  root 'welcome#example_inline'

  get 'head', to: 'welcome#example_in_head'
  get 'inline', to: 'welcome#example_inline'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :find_user

  def example_inline
  end

  def example_in_head
  end

  private

  def find_user
    @user = User.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def obj_as_js_var(var_name, obj, content_for_name = nil)
    str = "var #{var_name} = #{obj.to_json}"
    output = javascript_tag(str, type: 'text/javascript')
    if content_for_name
      content_for content_for_name, output
    else
      output
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>So03022016</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= content_for(:javascript) if content_for?(:javascript) %>
  <%= csrf_meta_tags %>
</head>
<body>
<h3>application.js is included at the bottom of the page, after rendering the view<br />
which renders the JS in either the head using content_for or somewhere in the view.</h3>
<%= link_to 'inline example', inline_path %> |
<%= link_to 'in head example', head_path %>
<%= yield %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/welcome/example_in_head.erb
<% obj_as_js_var :user, @user, :javascript %>
<p>Here, the injected JS through obj_as_js_var will be injected into the head<br />
this makes the variables available to the later included application.js</p>
<div id="result"></div>

app/views/welcome/example_inline.erb
<%= obj_as_js_var :user, @user %>
<p>Here, the JS gets injected directly in the page wherever the call to obj_as_js_var is used<br />
all JS that comes after this will be able to use the user var</p>
<div id="result"></div>